### ISSUE TITLE
Installation on Windows failed "cannot open input file curl.lib"

### ISSUE THREAD

**Issue by poliklosio** [Pure-D/serve-d#10]
I downloaded VS Code and attempted adding code-d serve-d beta today (at the time of writing this).
I installed ldc from this page: https://github.com/ldc-developers/ldc/releases/tag/LDC-Win64-master
as recommended here: https://wiki.dlang.org/Latest_LDC_binaries_for_Windows

This is the output log from VS Code:

Installing into C:\Users\piotr\AppData\Roaming\code-d\bin
Removing old version
Removed old version
> git clone --recursive https://github.com/Pure-D/serve-d.git serve-d
Cloning into 'serve-d'...
> dub upgrade
Upgrading project in C:\Users\piotr\AppData\Roaming\code-d\bin\serve-d
Re-installing branch based dependency workspace-d ~master
Removed package: 'workspace-d'
Fetching workspace-d ~master (getting selected version)...
Re-installing branch based dependency dscanner ~master
Removed package: 'dscanner'
Fetching dscanner ~master (getting selected version)...
> dub build --build=release --compiler=ldc2 --combined
WARNING: A deprecated branch based version specification is used for the dependency workspace-d. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
Performing "release" build using ldc2 for x86_64.
serve-d ~master: building configuration "application"...
..\..\..\dub\packages\painlesstraits-0.2.0\painlesstraits\source\painlesstraits.d(12,30): Deprecation: std.traits.Identity(alias A) is not visible from module painlesstraits
..\..\..\dub\packages\painlesstraits-0.2.0\painlesstraits\source\painlesstraits.d(12,30): Deprecation: std.traits.Identity(alias A) is not visible from module painlesstraits
..\..\..\dub\packages\painlesstraits-0.2.0\painlesstraits\source\painlesstraits.d(69,34): Deprecation: std.traits.Identity(alias A) is not visible from module painlesstraits
..\..\..\dub\packages\painlesstraits-0.2.0\painlesstraits\source\painlesstraits.d(12,30): Deprecation: std.traits.Identity(alias A) is not visible from module painlesstraits
..\..\..\dub\packages\painlesstraits-0.2.0\painlesstraits\source\painlesstraits.d(12,30): Deprecation: std.traits.Identity(alias A) is not visible from module painlesstraits
..\..\..\dub\packages\painlesstraits-0.2.0\painlesstraits\source\painlesstraits.d(69,34): Deprecation: std.traits.Identity(alias A) is not visible from module painlesstraits
C:\D\LDC-master-4450-x64\bin\..\include\d\std\uri.d(338,19): Deprecation: function std.utf.toUTF8 is deprecated - To be removed November 2017. Please use std.utf.encode instead.
..\..\..\dub\packages\ddmp-0.0.1-0.dev.2\ddmp\source\ddmp\patch.d(109,18): Deprecation: ddmp.diff.max is not visible from module patch
..\..\..\dub\packages\ddmp-0.0.1-0.dev.2\ddmp\source\ddmp\patch.d(109,50): Deprecation: ddmp.diff.min is not visible from module patch
..\..\..\dub\packages\ddmp-0.0.1-0.dev.2\ddmp\source\ddmp\patch.d(115,21): Deprecation: ddmp.diff.max is not visible from module patch
..\..\..\dub\packages\ddmp-0.0.1-0.dev.2\ddmp\source\ddmp\patch.d(121,51): Deprecation: ddmp.diff.min is not visible from module patch
..\..\..\dub\packages\ddmp-0.0.1-0.dev.2\ddmp\source\ddmp\patch.d(303,32): Deprecation: ddmp.diff.min is not visible from module patch
..\..\..\dub\packages\ddmp-0.0.1-0.dev.2\ddmp\source\ddmp\patch.d(305,32): Deprecation: ddmp.diff.min is not visible from module patch
..\..\..\dub\packages\ddmp-0.0.1-0.dev.2\ddmp\source\ddmp\patch.d(450,38): Deprecation: ddmp.diff.min is not visible from module patch
..\..\..\dub\packages\ddmp-0.0.1-0.dev.2\ddmp\source\ddmp\patch.d(469,35): Deprecation: ddmp.diff.max is not visible from module patch
..\..\..\dub\packages\ddmp-0.0.1-0.dev.2\ddmp\source\ddmp\patch.d(529,3): Deprecation: ddmp.diff.enforce is not visible from module patch
C:\D\LDC-master-4450-x64\bin\..\include\d\std\uri.d(323,19): Deprecation: function std.utf.toUTF8 is deprecated - To be removed November 2017. Please use std.utf.encode instead.
LINK : fatal error LNK1181: cannot open input file 'curl.lib'
Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\link.exe failed with status: 1181
ldc2 failed with exit code 1181.
Failed to install serve-d (Error code 2)

Building another project with dub build --compiler=ldc2 works fine

**Comment by WebFreak001** [comment]
Try compiling serve-d manually, when I release it properly it will ship with prebuilt binaries so that wont be a problem anymore. Did it include curl.lib in the lib files?

**Comment by poliklosio** [comment]
Same problem happens when I try to compile serve-d manually (git clone --recursive + dub build --compiler=ldc2).
serve-d doesn't have any lib files that I know of.
Dmd does have curl.lib in the installation. Ldc does not have curl.lib, although it does have curl.dll, but it shouldn't matter because building other projects with ldc works fine.

In any case I cannot make this work on Windows, because every time I reload the serve-d extension in VS Code it recompiles, so even if I try to build it manually it will be overwritten.

The old Code-d extension works fine though.

**Comment by WebFreak001** [comment]
Yeah the old code-d extension has precompiled binaries but will probably suffer under the same issue. Can you try if compiling [Pure-D/workspace-d](https://github.com/Pure-D/workspace-d) with the same command works?

Also try compiling a simple hello world program with std.net.curl imported and calling some function like download

**Comment by WebFreak001** [comment]
try installing visual studio build tools
