### ISSUE TITLE
How I can launch this with Emacs lsp-mode?

### ISSUE THREAD

**Issue by route616** [Pure-D/serve-d#109]
I installed lsp-mode & d-mode and wrote the following to the config:
```emacs-lisp
(lsp-register-client
 (make-lsp-client
  :new-connection (lsp-stdio-connection '("~/.dub/packages/serve-d-0.6.0/serve-d/serve-d"))
  :major-modes '(d-mode)
  :server-id 'serve-d))
```
In response, writes to the log:
"Symbol's function definition is void: lsp-register-client"

**Comment by WebFreak001** [comment]
you need to consult the lsp-mode documentation for that, but for what you have there it looks like setup is correct. Also try grabbing the latest beta serve-d release from https://github.com/Pure-D/serve-d/releases/tag/v0.7.0-beta.4

**Comment by route616** [comment]
> you need to consult the lsp-mode documentation for that, but for what you have there it looks like setup is correct. Also try grabbing the latest beta serve-d release from https://github.com/Pure-D/serve-d/releases/tag/v0.7.0-beta.4

Did not help. Doesn't work with `dls` either. I wrote a call to `lsp-mode` developers. Perhaps your server doesn't fully implement the protocol?
