### ISSUE TITLE
The debug messages are printed by default

### ISSUE THREAD

**Issue by aminya** [Pure-D/serve-d#112]
Even in production a lot of warning messages are printed. 

Is there an environment variable to set to suppress these messages? 

![image](https://user-images.githubusercontent.com/16418197/109066687-09c41100-76b3-11eb-8107-bcbd4ed03735.png)

**Comment by WebFreak001** [comment]
the global log level should only be trace when compiled in debug mode. Nightlys are built with release-debug, so they have debug mode on but are release builds.

**Comment by aminya** [comment]
Oh, I see. I was using the nightlies and that is why.
