### ISSUE TITLE
serve-d not working in Qt Creator Language Client plugin

### ISSUE THREAD

**Issue by magiruuvelvet** [Pure-D/serve-d#116]
[Qt Creator](https://github.com/qt-creator/qt-creator) (an IDE mainly for C++ using clangd for code completion) has support for language servers to easily integrate support for other programming languages using its official language client plugin. Qt Creator is able to query the capabilities of serve-d and shows its features, but I can't get any code completion to work at all. Also `serve-d` doesn't seem to start an instance of `dcd-server`. It does so when using VS Code with `code-d`, so the language server is at least confirmed to be working on my system. Not sure if there must be an additional request sent from the editor to start DCD or if it is started automatically. I can customize the `initialize` request in the LSP options, but that feature is not documented at all so I can't quite figure out the correct syntax or format.

**Environment**
- Gentoo Linux
- Qt Creator 4.14.0
- serve-d version 4296bf53 (`/usr/local/bin/serve-d`)
- DCD v0.13.1 (`/usr/local/bin/dcd-server`, `/usr/local/bin/dcd-client`)
- D compiler: LDC2 1.25.0 (based on DMD v2.095.1) (`/usr/bin/ldc2`)

I don't use the dlang overlay in Gentoo. I have made my own ldc2 ebuild and only one D compiler and runtime installed in `/usr`.

Qt Creator won't let me copy the language server capabilities and there is no logging in the terminal so I'm posting this screenshot.
![スクリーンショット_20210227_181329](https://user-images.githubusercontent.com/13280758/109394496-9bd44f80-7927-11eb-9a20-620617975ecd.png)

**Extra Notes**
I'm currently updating to Qt Creator 4.14.1 as I'm writing this. There were 2 interesting commits which are claiming to fix code completion with language servers. I will update the issue later.\
**EDIT:** Just updated to 4.14.1, still not working :(

Debugging language servers in Qt Creator is a pain, so that's all the info I got. If you need more information let me know.

**Comment by WebFreak001** [comment]
there are newer nightly builds, try those as they fixed a LSP compatibility issue

**Comment by magiruuvelvet** [comment]
I just tried current master of Qt Creator and its still not starting `dcd-server` and no code completion.

**Comment by WebFreak001** [comment]
do you have any LSP logs in Qt Creator? those would help pin down the issue.

They start similar to this:
```
2021-02-27T14:27:55.108 [trace] app.d:119:main Features fulfilled
2021-02-27T14:27:55.108 [trace] app.d:128:main Interactive HTTP downloads handled via editor
2021-02-27T14:27:55.108 [trace] app.d:134:main Auto-implement interface supports snippets
2021-02-27T14:27:55.108 [trace] app.d:140:main Context snippets handled by serve-d
2021-02-27T14:27:55.108 [trace] app.d:146:main Discoverying & emitting unittests for language client
serve-d v0.7.0-beta.4 with workspace-d v3.5.0
Included features: "d", "workspaces"
Built: Fri Jan 22 12:57:05 2021
with compiler Digital Mars D v2.94 on linux littleEndian
dub, dfmt and dscanner are bundled within (compiled in)
2021-02-27T14:27:55.109 [trace] serverbase.d:269:run Started reading from stdin
2021-02-27T14:27:55.109 [trace] serverbase.d:275:run RPC started
2021-02-27T14:27:55.130 [trace] serverbase.d:99:processRequest Initializing
```

**Comment by magiruuvelvet** [comment]
The only type of logs produced are:
```plain
LanguageClient D (serve-d) for hello: Log: [progress] [00001.347] [configLoad]: file:///path/to/workspace
LanguageClient D (serve-d) for hello: Log: [progress] [00001.348] [globalStartup]: Initializing serve-d...
LanguageClient D (serve-d) for hello: Log: [progress] [00001.353] [workspaceStartup] 0 / 1: file:///path/to/workspace
LanguageClient D (serve-d) for hello: Log: [progress] [00001.353] [completionStartup] 0 / 1: file:///path/to/workspace
LanguageClient D (serve-d) for hello: Log: [progress] [00001.353] [configFinish]
```

As said earlier, debugging LSP in Qt Creator is a pain, as it doesn't produce any useful logs and there isn't even output in the terminal either. I will try to somehow extract output from it.

**Comment by WebFreak001** [comment]
did you compile serve-d in debug mode / got a nightly build?

it logs in verbose so you might get more output if you can find the serve-d output anywhere.

**Comment by magiruuvelvet** [comment]
I'm currently patching serve-d a bit and adding random `append(file, data)` calls to see what qt creator is sending and what serve-d is responding. Eventually I will find the culprint in the produced log file. I couldn't spy on the pipe so this solution works too I guess.

The only thing I figured out by now is that serve-d stops sending responses after `[configFinish]` happened.

**Comment by WebFreak001** [comment]
serve-d uses std.experimental.logger for all logging: https://dlang.org/phobos/std_experimental_logger.html

```d
shared static this()
{
    sharedLog = new FileLogger("New_Default_Log_File.log");
}
```
at the start of app.d should make all log go into that file.

**Comment by magiruuvelvet** [comment]
Thanks, I finally got a log. I hope it helps. An interesting line I noticed `Providing no completion for unknown language ID .` - I don't get this message when using `code-d` and VS code.

[serve-d.log](https://github.com/Pure-D/serve-d/files/6055456/serve-d.log)

**Comment by WebFreak001** [comment]
ah that will be the issue then. I can add an optional startup parameter to assume all unknown files are D files for editors like this.

**Comment by WebFreak001** [comment]
please confirm if working now, (falling back to file extension with empty language id now)

reopen if it doesn't work at all, create new issue if you find new bugs.

**Comment by magiruuvelvet** [comment]
It works now :)

It shows errors and warnings now too.
