### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by emi2k01** [Pure-D/serve-d#117]
Branch: master

DMD64 D Compiler v2.095.0

DUB version 1.23.0, built on Oct  8 2020

```
## Warning for package serve-d, configuration unittest-optimized ##

The following compiler flags have been specified in the package description
file. They are handled by DUB and direct use in packages is discouraged.
Alternatively, you can set the DFLAGS environment variable to pass custom flags
to the compiler, or use one of the suggestions below:

debugInfo: Call DUB with --build=debug
optimize: Call DUB with --build=release
unittests: Call DUB with --build=unittest

Selected package vibe-d 0.9.3 does not match the dependency specification >=0.7.30 <=0.9.0 (optional) in package dub. Need to "dub upgrade"?
Selected package vibe-d 0.9.3 does not match the dependency specification >=0.7.30 <=0.9.0 (optional) in package dub. Need to "dub upgrade"?
Invalid source/import path: /home/emi2k01/.dub/packages/dfmt-0.13.0/dfmt/bin
Running pre-generate commands for dfmt...
/bin/sh: line 1: rdmd: command not found
Command failed with exit code 127: rdmd "/home/emi2k01/.dub/packages/dfmt-0.13.0/dfmt/dubhash.d"
```

**Comment by emi2k01** [comment]
My bad.

I thought the error was caused by `Selected package vibe-d 0.9.3 does not match...` but it seems to just be a warning.

I had to install dtools but that is not mentioned in the README.

**Comment by WebFreak001** [comment]
> /bin/sh: line 1: rdmd: command not found
> Command failed with exit code 127: rdmd "/home/emi2k01/.dub/packages/dfmt-0.13.0/dfmt/dubhash.d"

The error was rdmd not being installed but was used as a dependency from dfmt, how did you install dmd? It normally comes with dmd.

**Comment by emi2k01** [comment]
My bad. I installed the `dmd` package from the AUR but the correct one is `dlang` that includes `dmd` and other tools.
