### ISSUE TITLE
The serve-d project needs a logo :)

### ISSUE THREAD

**Issue by ghuntley** [Pure-D/serve-d#125]
Howdy folks,

I'm doing some marketing activities for https://www.gitpod.io and I would like to feature the serve-d project at an upcoming conference organised by @gitpod-io.

**question:** does the project have a logo?
**ask:** can you please provide a logo in the next couple of days?

**Comment by WebFreak001** [comment]
hmm there is a code-d logo (the respective vscode extension using serve-d) which is kind of used for serve-d right now, though if you want to differentiate between code-d and serve-d that's not a solution.

If you only want to feature these D tools in common it would work though.

Logo is here: https://github.com/Pure-D/code-d/blob/master/images/dlogo-square.png (also available as svg)

**Comment by WebFreak001** [comment]
closing this as the code-d logo is basically the serve-d logo
