### ISSUE TITLE
No annotation for wrong method call

### ISSUE THREAD

**Issue by gizmomogwai** [Pure-D/serve-d#133]
e.g. serve-d is not complaining if the standard hello world program is "adjusted" like that:

    import std.stdio;

    void main()
    {
        writeln_not_existing("Edit source/app.d to start your project.");
    }

But it should complain, that writeln_not_existing is an unknown identifier.

    source/app.d(5,5): Error: undefined identifier `writeln_not_existing`

**Comment by WebFreak001** [comment]
when it's a dub project and you press save it builds the project and shows that error.
