### ISSUE TITLE
Dub errors are not user facing

### ISSUE THREAD

**Issue by aminya** [Pure-D/serve-d#137]
I had an error in my dub.json which I had spelled out one of the dependencies wrongly. But all I was getting was this:

![image](https://user-images.githubusercontent.com/16418197/119432238-98a7f000-bcd9-11eb-90c4-0a3a0197b410.png)

After using the developer log, I found out the actual problem. 
![image](https://user-images.githubusercontent.com/16418197/119432136-6eeec900-bcd9-11eb-88d4-dc26972fb68b.png)

**Comment by WebFreak001** [comment]
fixed in nightly, also currently working on more detailed error messages

**Comment by aminya** [comment]
Ah, thank you!
