### ISSUE TITLE
Serve-d keep asking for re-downloading DCD

### ISSUE THREAD

**Issue by vushu** [Pure-D/serve-d#139]
Hi thanks for this awesome language server :)

I am trying to implement serve-d into a coc extension
I keep getting the message below every instance, even though I already have it installed.

```
DCD is outdated. (target=0.13.2, installed=none)
(1) Download DCD:

```

I can see that the files exist in:

```
vushu@pop-os:~/.local/share/code-d/bin$ ls
dcd-client  dcd-server  dcd-v0.13.2-linux-x86_64.tar.gz
```

How do I resolve this thanks.

**Comment by WebFreak001** [comment]
do your settings contain the path to the code-d/bin/dcd-* files? I don't think it tries to look there by default

**Comment by vushu** [comment]
Hi @WebFreak001  

I am not sure about, how to do it, I tried 
```
 
    const updateServerParams = {
      section: 'd.dcdServerPath',
      value: '.config/coc/coc-dlang-data',
      global: 'true'

    };

    client.sendRequest("coded/updateSetting", updateServerParams).then((data:any) => {
      window.showPrompt('something happened');

    });

  });

```

I get methodNotfound Error

**Comment by WebFreak001** [comment]
it's the standard LSP workspace configuration where it takes the settings from.

The client should automatically send it on startup https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeConfiguration or serve-d will attempt to fetch it from the client if the `configuration` capability is sent by the client https://microsoft.github.io/language-server-protocol/specification#workspace_configuration

**Comment by vushu** [comment]
Thanks I have studied LSP a bit. I still have little problem, serve-d tries to download dcd v.0.13.2, but It fails, I suspect that v0.13.2 doesn't have any binary folders


![image](https://user-images.githubusercontent.com/1658625/120425120-f093c600-c36d-11eb-8af1-00cfbf698df4.png)

![image](https://user-images.githubusercontent.com/1658625/120428013-3901b280-c373-11eb-9bc7-0d3d8ad82c90.png)

**Comment by dvcentic** [comment]
Hi @WebFreak001, It now works, but I cant figure out how to setup serve-d to addImport for dub packages, but it works for std imports.

**Comment by vushu** [comment]
Hi @WebFreak001, It now works since the binaries now exists,
Just a quick question: how do I setup serve-d to addImport for dub packages? Iit works for std imports, but I simply can't figure it out,
 
thanks.

**Comment by WebFreak001** [comment]
serve-d will automatically find the dependencies, however when you add new ones you first need to download them using `dub upgrade` or `dub build`, then you have to either restart serve-d or send the `served/updateImports` LSP requests. (this is what is done in code-d on the little refresh button on the custom DUB dependency tree)

**Comment by vushu** [comment]
Thanks for answering my questions, you can close this issue :)
