### ISSUE TITLE
serve-d installation hangs

### ISSUE THREAD

**Issue by Barugon** [Pure-D/serve-d#14]
When I open a D project folder for the first time after installing the serve-d extension (0.17.5), I get the message "Upgrading project in /home/ivan/.local/share/code-d/bin/serve-d" in the output window and nothing else happens. When I check the Git output, I have a bunch of messages that say:
```
git rev-parse --show-toplevel
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by WebFreak001** [comment]
the git output has nothing to do with this, it's the vscode internal git output. Can you check the `code-d & serve-d Output`? If that one is not there the `serve-d Installation Progress` output tab instead

**Comment by Barugon** [comment]
The ```code-d & serve-d``` output isn't there because it hasn't been fully installed an started yet. The ```code-d installation progress``` output has ```Upgrading project in /home/ivan/.local/share/code-d/bin/serve-d``` perpetually.

**Comment by Barugon** [comment]
This is on Linux BTW.

**Comment by WebFreak001** [comment]
how long did you leave it for? That's dub outputting that message. It might be that it has some deadlock with dscanner, which it should print if you leave it for like 5 minutes

**Comment by Barugon** [comment]
I left it for more than an hour. No change.

**Comment by WebFreak001** [comment]
```
dub --version
dmd --version
```

**Comment by Barugon** [comment]
DUB version 1.6.0, built on Nov 29 2017
DMD64 D Compiler v2.077.1

**Comment by Barugon** [comment]
Do you need the output from ```dub update -v``` or are you able to replicate this?

**Comment by Barugon** [comment]
It looks to me like it's unable to find vibe-d and just hangs.

**Comment by WebFreak001** [comment]
does the issue still occur? Maybe dub registry was down

**Comment by Barugon** [comment]
It's definitely hanging when upgrading workspace-d. I haven't narrowed it down to which dependency though.

**Comment by Barugon** [comment]
If I use ```dub upgrade --vverbose```, it'l eventually start spitting out this in an infinite loop:
```
Interation (ci=30) fluent-asserts 0.7.1, ddmp 0.0.1-0.dev.3, unit-threaded 0.7.32, libdparse 0.7.1, experimental_allocator 2.70.0-b1, painlessjson 1.3.8, painlesstraits 0.2.0, dunit 1.0.14, libddoc 0.2.0, workspace-d ~master, dfmt 0.6.0-alpha.1, dub 1.6.0, vibe-d 0.8.1, libevent 2.0.2+2.0.16, libasync 0.8.3, memutils 0.4.9, vibe-core 1.3.0, eventcore 0.8.26, taggedalgebraic 0.10.7, stdx-allocator 2.77.0, botan 1.12.9, botan-math 1.0.3, openssl 1.1.6+1.0.1g, libev 5.0.0+4.04, diet-ng ~master, libhttp2 0.2.5, inifiled 1.0.2, standardpaths 0.8.0, xdgpaths 0.2.2, isfreedesktop 0.1.1, dscanner 0.4.1 (C), dsymbol 0.2.9 (C), emsi_containers 0.5.3 (C), eventsystem 1.2.0 (C)
Dependency vibe-d:http -> diet-ng ~>1.2 mismatches with selected version ~master (ci=24)
Dependency dscanner -> libdparse >=0.7.2-alpha.3 <0.8.0 mismatches with selected version 0.7.1 (ci=30)
```

**Comment by WebFreak001** [comment]
Have you tried deleting dub.selections.json yet? _The source of all evil and all dub build issues ever_

**Comment by Barugon** [comment]
There's no dub.selections.json in the serve-d folder.

**Comment by Barugon** [comment]
I installed Visual Studio Code on a Windows PC then added the serve-d extension and got the same issue.

**Comment by WebFreak001** [comment]
huh you are right, happens to me too. Seems like a dub issue, I will investigate further

**Comment by WebFreak001** [comment]
Can you reproduce that dub issue?

**Comment by Barugon** [comment]
@WebFreak001
It's good now.

**Comment by ALENTL** [comment]
> 

![image](https://user-images.githubusercontent.com/82425585/149766029-4134cd8d-8f03-48c6-b396-1b4bcac88714.png)

**Comment by WebFreak001** [comment]
@ALENTL I'm not sure what you wanna do with that release.sh

Delete `~/.local/share/code-d/bin/serve-d` (it should not be a folder)

Create a new issue if you have other issues
