### ISSUE TITLE
Support nvim-lsp instead of a seprate vim plugins

### ISSUE THREAD

**Issue by mTvare6** [Pure-D/serve-d#141]
Instead of packing a seprate plugin, incase of neovim, it would be better to have a [nvim-lspconfig module](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md) so its a single plugin starting up which saves time, and allows a user to rely on single plugin

**Comment by WebFreak001** [comment]
how can I include that in serve-d? is this really the correct place for this issue?

Additionally given that there are extra non-standard functionalities that the clients may implement, having a plugin makes sense once they do implement them.

**Comment by mTvare6** [comment]
Oh, nvim lsp is the just a "wrapper" or collection of lsp's, it includes them and adds basic configuration
If the lsp follows the [VScode LSP protocol](https://docs.microsoft.com/en-us/visualstudio/extensibility/language-server-protocol?view=vs-2019), they should be easy to add
Few example prs:
https://github.com/neovim/nvim-lspconfig/pull/950
https://github.com/neovim/nvim-lspconfig/pull/707
https://github.com/neovim/nvim-lspconfig/pull/883
