### ISSUE TITLE
Sometimes symbols from a module doesn't get updated

### ISSUE THREAD

**Issue by RUSshy** [Pure-D/serve-d#146]
---
EDIT:

this specific post is a different issue https://github.com/dlang-community/DCD/issues/648
for the actual issue, check replies bellow
---

Let's take this example:

```D
struct Entity
{
    Tes   // <- i don't get completion for Test
}

struct Test
{
}
```

But if i put the ``struct Test`` above Entity, then it works

![image](https://user-images.githubusercontent.com/18348637/125176025-94c02680-e1d0-11eb-8bef-f044bfdffb32.png)

**Comment by RUSshy** [comment]
I think the issue is something else

I just had a situation where when i make changes to a module, then DCD-SERVER doesn't know about the changes if i try to get completion from another module

Something doesn't trigger DCD to update symbols..

I don't know what it could be exactly, it didn't happen in the past

**Comment by RUSshy** [comment]
The symbol is visible in the module, i can the function name in the Outline window, so maybe it's a caching issue?

I'm gonna try to figure out how it is done in the code

**Comment by WebFreak001** [comment]
I often experience this too, but it seems random when it happens. Not sure if this is a DCD issue

**Comment by RUSshy** [comment]
i removed caching here: https://github.com/Pure-D/serve-d/blob/master/source/served/commands/symbol_search.d

but the issue still persists

you may be right, it could be an issue with DCD.. i'll try to dig deeper

**Comment by RUSshy** [comment]
How do i enable DCD-server output in VSCode?

**Comment by WebFreak001** [comment]
it should print stuff by default, but I may have put it behind verbose output only so you need to add `"serve-d.trace.server": "verbose"` to your user settings JSON (it will be grayed out, saying it doesn't exist, but ignore that) and reload

**Comment by RUSshy** [comment]
It's very verbose, there should be a way to limit stuff to dcd-server for debugging purposes

**Comment by RUSshy** [comment]
This issue seems to happen onl when modules import each other

```D
module a;

import module b;

void test() // <-- i just typed this
{}
```

```D
module b;

import module a;


tes // <-- now i try to get autocomplete here and it doesn't work, the ``module a`` doesn't seems to be updated with new changes
```

**Comment by RUSshy** [comment]
Well i give up, i can't wrap my head around DCD code base

The issue is either DCD or DSymbol, something weird with ``ModuleCache``, probably the recursive guard, https://github.com/dlang-community/dsymbol/blob/master/src/dsymbol/modulecache.d#L166

Hopefully someone more knowledgeable can figure out what's not working correctly

**Comment by RUSshy** [comment]
One possible solution would be to clear the module cache every time we do a completion request

I'm done with DCD for today, if someone want to give it a try, go ahead!

**Comment by RUSshy** [comment]
I had some free time so i decided to tinker a little more and i managed to find who the culprit is, and it's indeed the ``ModuleCache``

Clearing it, and rimporting files at each completion request gives proper results

However this is not a solution since it reparses everything this adds ton of useless disk (read) operations, and is slow

So we have 2 solutions:

- Figure out exactly what piece of code inside the [ModuleCache](https://github.com/dlang-community/dsymbol/blob/master/src/dsymbol/modulecache.d)
- Rewrite the ModuleCache

I can't rewrite it since i'm not familiar with the code base, and to be honest, i don't want to allocate much time doing it

So i'll continue tinker a little more..

At least we now know what exactly is the issue..

**Comment by RUSshy** [comment]
And i fixed the issue!

It requires changes in multiple repo

- DSymbol: https://github.com/dlang-community/dsymbol/pull/161
- DCD: https://github.com/dlang-community/DCD/pull/647
- WorkspaceD: https://github.com/Pure-D/workspace-d/pull/112

Now symbols properly updated whenever the module was changed (simply just by rescanning the imports), then ModuleCache will properly figure out what file needs to be reloaded/reparsed

**Comment by WebFreak001** [comment]
I think the issue might occur when a file in that cyclic pattern is first parsed because of the loading process but afterwards doesn't catch modifications?

**Comment by RUSshy** [comment]
That's possible, i spent many hours already trying to figure what was wrong with that logic, even allowing multiple recursion didn't work, the workaround will do it for me until i can afford spending more time debugging this issue properly

**Comment by RUSshy** [comment]
I found what the issue is and have a reproducible code

It is due to public imports

https://github.com/dlang-community/DCD/issues/646
