### ISSUE TITLE
Binary distributions and documentation

### ISSUE THREAD

**Issue by mickaelistria** [Pure-D/serve-d#16]
To facilitate integration of the language server in the various tools, it would make integration much easier to provide binary builds of the language server and documentation on how to start it.

**Comment by WebFreak001** [comment]
everything is setup for binary distributions, I already have a manual build server for workspace-d (linux and windows), once serve-d is stable I will set that up too and document the extra commands (not the basic lsp).

**Comment by WebFreak001** [comment]
only missing documentation now
