### ISSUE TITLE
serve-d on windows 10 crashes 

### ISSUE THREAD

**Issue by dangbinghoo** [Pure-D/serve-d#17]
I just compiled serve-d using ldc2 on windows 10 using below dub cmd:

dub build --build=release  --compiler=ldc2 --force

And after running vs code, I got the following error :

std.getopt.GetOptException@C:\D\ldc2-1.6.0-win64-msvc\bin\..\import\std\getopt.d(789): Unrecognized option --lang
----------------
0x00007FF78EA895DD
0x00007FF78EA89336
0x00007FF78EA87E7C
0x00007FF78EA709E1
0x00007FF78E883002
0x00007FF78E88280F
0x00007FF78E881E95
0x00007FF78E878FAF
0x00007FF78EA77665
0x00007FF78EA91719
0x00007FFAA9C81FE4 in BaseThreadInitThunk
0x00007FFAAAECEF91 in RtlUserThreadStart
[Info  - 22:49:03] Connection to server got closed. Server will restart.

std.getopt.GetOptException@C:\D\ldc2-1.6.0-win64-msvc\bin\..\import\std\getopt.d(789): Unrecognized option --lang
----------------
0x00007FF78EA895DD
0x00007FF78EA89336
0x00007FF78EA87E7C
0x00007FF78EA709E1
0x00007FF78E883002
0x00007FF78E88280F
0x00007FF78E881E95
0x00007FF78E878FAF
0x00007FF78EA77665
0x00007FF78EA91719
0x00007FFAA9C81FE4 in BaseThreadInitThunk
0x00007FFAAAECEF91 in RtlUserThreadStart
[Info  - 22:49:03] Connection to server got closed. Server will restart.

std.getopt.GetOptException@C:\D\ldc2-1.6.0-win64-msvc\bin\..\import\std\getopt.d(789): Unrecognized option --lang
----------------
0x00007FF78EA895DD
0x00007FF78EA89336
0x00007FF78EA87E7C
0x00007FF78EA709E1
0x00007FF78E883002
0x00007FF78E88280F
0x00007FF78E881E95
0x00007FF78E878FAF
0x00007FF78EA77665
0x00007FF78EA91719
0x00007FFAA9C81FE4 in BaseThreadInitThunk
0x00007FFAAAECEF91 in RtlUserThreadStart
[Info  - 22:49:04] Connection to server got closed. Server will restart.

std.getopt.GetOptException@C:\D\ldc2-1.6.0-win64-msvc\bin\..\import\std\getopt.d(789): Unrecognized option --lang
----------------
0x00007FF78EA895DD
0x00007FF78EA89336
0x00007FF78EA87E7C
0x00007FF78EA709E1
0x00007FF78E883002
0x00007FF78E88280F
0x00007FF78E881E95
0x00007FF78E878FAF
0x00007FF78EA77665
0x00007FF78EA91719
0x00007FFAA9C81FE4 in BaseThreadInitThunk
0x00007FFAAAECEF91 in RtlUserThreadStart
[Info  - 22:49:05] Connection to server got closed. Server will restart.

std.getopt.GetOptException@C:\D\ldc2-1.6.0-win64-msvc\bin\..\import\std\getopt.d(789): Unrecognized option --lang
----------------
0x00007FF78EA895DD
0x00007FF78EA89336
0x00007FF78EA87E7C
0x00007FF78EA709E1
0x00007FF78E883002
0x00007FF78E88280F
0x00007FF78E881E95
0x00007FF78E878FAF
0x00007FF78EA77665
0x00007FF78EA91719
0x00007FFAA9C81FE4 in BaseThreadInitThunk
0x00007FFAAAECEF91 in RtlUserThreadStart
[Error - 22:49:05] Connection to server got closed. Server will not be restarted.

**Comment by WebFreak001** [comment]
uh can you verify that you actually really compiled serve-d and not workspace-d? (check name in dub.json)

**Comment by WebFreak001** [comment]
Reopen when you sent me the output of `serve-d --help` and `serve-d --version`
