### ISSUE TITLE
Crash on startup on Windows - Exception code: 0xc0000417

### ISSUE THREAD

**Issue by Ekopalypse** [Pure-D/serve-d#176]
Running serve_d (latest version 0.7 ) from Notepad++ crashes immediately after starting.
The only line logged is
```
2021-11-22T12:34:51.835 [trace] source\app.d:146:main Features fulfilled
```
EventVwr:
```
Faulting application name: serve-d.exe, version: 0.0.0.0, time stamp: 0x6199326a
Faulting module name: serve-d.exe, version: 0.0.0.0, time stamp: 0x6199326a
Exception code: 0xc0000417
Fault offset: 0x0000000000504ab2
Faulting process id: 0x1c64
Faulting application start time: 0x01d7df94f585eded
Faulting application path: D:\ProgramData\Compiler\dmd2\windows\bin64\serve-d.exe
Faulting module path: D:\ProgramData\Compiler\dmd2\windows\bin64\serve-d.exe
```

However, execution via the cmd shell works.

```
C:\Windows\System32>D:\ProgramData\Compiler\dmd2\windows\bin64\serve-d.exe --wait true --logfile d:\serve_d.log --loglevel all
serve-d v0.7.0 with workspace-d v3.6.1
Included features: "d", "workspaces"
Built: Sat Nov 20 17:36:41 2021
with compiler LDC v2.98 on win64 littleEndian
dub, dfmt and dscanner are bundled within (compiled in)
```

Any ideas what could be causing this? Note that other language servers can be used from Npp.

Update: happens under Windows7 x64

**Comment by WebFreak001** [comment]
I have never seen a crash like that, can you try attaching to serve-d.exe with visual studio if you have it installed? Using `--wait` you have 2 seconds to attach on startup.

You might need to compile serve-d from source using LDC or use a release from the nightly CI builds, which compiles in debug mode with optimization.

**Comment by RUSShyTwo** [comment]
Wich version fo notepad++ are you using? and wich LSP plugin?

**Comment by Ekopalypse** [comment]
@WebFreak001, thx for the quick reply.
I managed to compile the sources with ldc.
I'm not familiar with D, but it looks like there is something "unusual" with file locking?

![image](https://user-images.githubusercontent.com/47723516/142903903-26bb7d91-ed9d-4929-9178-a64fada19ee4.png)

In your release.bat there is a note that Windows 8 and higher is supported.
Is it simply a missing parameter/function call from Windows 7, the OS I am using?

@RUSShyTwo, Currently I am using Npp 8.1.3 and the [lsp client](https://github.com/Ekopalypse/NppLspClient/releases) I am trying to write.
Another [lsp client](https://sourceforge.net/p/kered13-notepad-plugins/code/ci/default/tree/) is being developed by Kered13.

**Comment by WebFreak001** [comment]
it looks like it tried writing to stderr but failed (it writes debug logs to stderr)

**Comment by Ekopalypse** [comment]
Oh - then it might be my problem

**Comment by Ekopalypse** [comment]
@WebFreak001 
Yes, that was it - thank you very much.
After I defined a valid error output handle, it no longer crashes.
Sorry for the unnecessary effort I caused.

**Comment by Ekopalypse** [comment]
I think it makes sense to handle stderr as other language servers might use this as well.
