### ISSUE TITLE
serve-d on M1 macOS is using 100% CPU (and killing my battery life :()

### ISSUE THREAD

**Issue by hatf0** [Pure-D/serve-d#185]
<img width="282" alt="Screen-Shot-2021-12-18-12-28-32" src="https://user-images.githubusercontent.com/15710074/146650298-f7c5d47e-f66d-4e16-8bb5-929c19fa65d0.png">

If I attach with `lldb`, and interrupt, the call stack is:
<img width="789" alt="Screen-Shot-2021-12-18-12-28-59" src="https://user-images.githubusercontent.com/15710074/146650315-5422440d-600a-4b17-ba53-810103f27905.png">

I'm not sure why `nanosleep` is resulting in such a high CPU usage...

**Comment by WebFreak001** [comment]
it might be doing something on other threads, if you still have it open, can you check if other threads are running?

**Comment by hatf0** [comment]
Got this bug to trigger again, so I'll just dump the backtraces of each thread here:

## Thread 2:
<img width="710" alt="Screen-Shot-2021-12-21-13-20-05" src="https://user-images.githubusercontent.com/15710074/146979334-7ecbebc8-3fbf-4c33-8dbc-dc868c79edea.png">

## Thread 3:
<img width="977" alt="Screen-Shot-2021-12-21-13-20-16" src="https://user-images.githubusercontent.com/15710074/146979365-1afd5d64-eb9d-4743-9446-736bd81a8850.png">

## Thread 4:
<img width="971" alt="Screen-Shot-2021-12-21-13-20-40" src="https://user-images.githubusercontent.com/15710074/146979404-7ec297e1-4152-487a-99d4-c9dfe1d3c7e9.png">

## Thread 5:
<img width="972" alt="Screen-Shot-2021-12-21-13-20-55" src="https://user-images.githubusercontent.com/15710074/146979430-27fcb419-1540-4ed4-94ac-bc8c6823327e.png">

## Thread 6:
![Screen-Shot-2021-12-21-13-21-23](https://user-images.githubusercontent.com/15710074/146979481-8732adb3-d318-4818-a264-834d06ebbef6.png)

## Thread 7:
<img width="733" alt="Screen-Shot-2021-12-21-13-21-39" src="https://user-images.githubusercontent.com/15710074/146979518-88cab074-5284-4677-9760-835ffa211cd2.png">

## Thread 8:
<img width="747" alt="Screen-Shot-2021-12-21-13-21-54" src="https://user-images.githubusercontent.com/15710074/146979532-c37d5d2a-ff74-4fce-8cd8-26410b24ab93.png">

## Thread 9:
![Screen-Shot-2021-12-21-13-22-07](https://user-images.githubusercontent.com/15710074/146979566-fd5e17e9-3514-4b5c-9695-09666930a427.png)

## Thread 10:
<img width="738" alt="Screen-Shot-2021-12-21-13-22-21" src="https://user-images.githubusercontent.com/15710074/146979589-daa50056-fabc-4bfc-8b07-2ab13b6ad094.png">

## Thread 11:
<img width="728" alt="Screen-Shot-2021-12-21-13-23-04" src="https://user-images.githubusercontent.com/15710074/146979702-f5949816-1c41-4ad3-8a76-6d4000250a8e.png">

## Thread 12:
<img width="578" alt="Screen-Shot-2021-12-21-13-23-17" src="https://user-images.githubusercontent.com/15710074/146979733-bf9c3c73-1d21-4274-ba00-eac85b646edf.png">

## Thread 13:
<img width="912" alt="Screen-Shot-2021-12-21-13-23-33" src="https://user-images.githubusercontent.com/15710074/146979770-56fe75d4-3e0a-47ca-8020-f51a65fd29be.png">

## Thread 14:
<img width="732" alt="Screen-Shot-2021-12-21-13-23-46" src="https://user-images.githubusercontent.com/15710074/146979799-35bd316f-53e5-46b1-9404-b604a803e7f1.png">

**Comment by WebFreak001** [comment]
seems like something might be causing an infinite loop in here: https://github.com/Pure-D/serve-d/blame/master/lsp/source/served/lsp/filereader.d

**Comment by Heromyth** [comment]
It's the same problem in Linux.

**Comment by WebFreak001** [comment]
fixed with #187, release incoming

**Comment by WebFreak001** [comment]
(actually untested if it actually fixes the issue, never reproduced the 100% issue before, but might help and improved API usage anyway)
