### ISSUE TITLE
Can not install without LDC2

### ISSUE THREAD

**Issue by Wulfklaue** [Pure-D/serve-d#2]
>Removing old version
> Removed old version
> git clone --recursive https://github.com/Pure-D/serve-d.git serve-d
>Cloning into 'serve-d'...
> dub upgrade
>Upgrading project in C:\Users\Benny\AppData\Roaming\code-d\bin\serve-d
>Re-installing branch based dependency workspace-d ~master
>Removed package: 'workspace-d'
>Fetching workspace-d ~master (getting selected version)...
> dub build --build=release **--compiler=ldc2 -**-combined
>Failed to invoke the compiler ldc2 to determine the build platform: '"ldc2"' is not recognized as an internal or external command,
>operable program or batch file.
>Failed to install serve-d (Error code 2)`

Fairly sure that most people will install DMD by default, not LDC ;)

**Comment by WebFreak001** [comment]
dmd does not work with workspace-d on windows, see https://github.com/Pure-D/code-d/issues/38

**Comment by Wulfklaue** [comment]
Well, that explains probably half my previous bug reports about code-d doing almost nothing useful ( beyond code highlights ).  *sigh*.

**Comment by WebFreak001** [comment]
huh how did you compile it then, I added a static assert that prevents compilation with dmd

**Comment by Wulfklaue** [comment]
"huh" is the correct answer because most of the time i was running DMD. At work and at home. I only ended up installing LDC one time at home and was annoyed with the installation process ( found it lacking ). Its been too long ago now but i can say that LDC was not installed for most of my code-d installations and attempts. Especially not at my work.

There is even one bug report and several mentioning in other reports, that i remember writing about how i always got "loading" popping up for a second but it never displayed anything useful.

Its one of the reason for my dislike for D these days. It always one thing or another that does not work properly. I do mean it that i wasted dozens of hours trying to get things working, trying to figure out why things did not work etc. In other languages it felt like the VSC plugins simply "worked" out of the box and D it was always fighting me. To the point that i end up manually fetching the sources and at time compiling things. Maybe that it why some things worked. Sorry but its been so long that i do not remember.

I noticed that serve-d was out and wanted to give it a try ( hoping that things improved ), to see this LDC message and thinking "not again".

**Comment by WebFreak001** [comment]
LDC is just downloading and extracting on windows assuming you have visual studio installed, I could probably make it auto setup

**Comment by Wulfklaue** [comment]
Its tiring when a programming language requires Visual Studio ( a A 2GB+ installation ) to be installed, simply because it needs the linker.  ;) 

Do not quote me on LDC but it involved ( in my case ) more then simply downloading and extracting on windows. But it has been 5 months ago, so i do not remember the issues.

Rust, Go, even .net Core ended up being more easy ( and that included running the beta with the whole json changeover :) ). Or maybe that is simply high sight that make it look more easy.

Do not even get me started on the cross platform compiling and documentation :) Anyway, i have too many issues with D these days to program in it anymore.

**Comment by WebFreak001** [comment]
cross compilation was always difficult with every language in my experience, not sure what you are comparing it against there and I think the documentation of D is far better than C/C++. The language is documented easily understandable and the standard library has its own place. There is also dpldocs.info for searching for documentation.

I know that LDC requires a big visual studio installation which also really annoys me but honestly I don't really care for developing on windows that much. I do want to support it to a certain degree but rather than rewriting the process functions with bare win32 implementations that don't hang up with DMD I would install LDC. I only use windows at work and in a VM so I implementing that win32 implementation would be way too annoying for me (at work I have other things to do most of the time and in a VM everything lags and is slow).

Maybe some commit in the past has fixed the windows issue though, I could add a test program to find out if the current platform is affected by that issue. If you want, try compiling serve-d with dmd. It will crash on the first compilation and tell you where the static assert is, then simply remove that one.

**Comment by vladimmi** [comment]
> Its tiring when a programming language requires Visual Studio ( a A 2GB+ installation ) to be installed, simply because it needs the linker. ;)

Actually, you can install Build Tools only, without Visual Studio itself. Also, afaik, it needs more than just a linker because LLVM on Windows doesnt provide C++ standard library or anything - it just uses MSVC ones. Not sure if that all is needed when you compile D-only code, though...

**Comment by Wulfklaue** [comment]
The fact that LDC is going to include the LLD linker for windows is a step in  the right direction of being Visual Studio Independent.

I gave LDC another try and figured out what was so frustrating about it on Windows. Yes, its a simple download and unzip of the folder. But after this you need to include it in your local path and then things get interesting.

Its not listed anywhere how, where, what ...  The official readme states "No installation is required, simply use the executables in the bin\ subfolder.". Well, that does NOT work with serve-d because serve-d can not find the executable ( what makes sense when you just drop it in a random folder somewhere ).

You need to include it in Windows its path and link to the bin folder for any program to be able to use it. And then you enter the wonderful world of bash. For example: 

@echo.
@echo Setting up 64-bit environment for using LDC 2 from %~dp0bin.
@echo.
@set PATH=%~dp0bin;%PATH%

Or 

setx LDC "C:\LDC\Bin" /m

This does not work when your path is over 1024 chars long. 

Settings a path is a bit more tricky on Windows then Linux. So your forced to go to the environment configuration and set the path manually in the interface. After you probably rebooted or logged out half a dozen times.  Please raise hand the amount of people who know to located the Environment Variables settings deep hidden in de Sytem Properties, Advanced tab :)   Its something that people "normally" rarely do under windows.

So not exactly the most friendly installation. DMD is way more friendly installation and does not suffer from those issues.

Also, after it was fixed serve-d failed to load after compilation and needed a VSC restart. Then DCD downloaded and compiled. And i am fairly sure that Serve-d is not working properly. While Dscanner is working, simple things like:

auto gpg2 = new Gpg2();
gpg2 *press dot* ... Loading ... nothing.

Ill see about finding the log tomorrow night because its now 03h and need to go to work in a few hours :(

**Comment by vladimmi** [comment]
> Please raise hand the amount of people who know to located the Environment Variables settings deep hidden in de Sytem Properties, Advanced tab :) Its something that people "normally" rarely do under windows.

Me, for example - probably that's because we are on GitHub that's not a place where "normal" people gather :D I'm sure programmers know how to tweak their environment.

**Comment by Wulfklaue** [comment]
> Me, for example - probably that's because we are on GitHub that's not a place where "normal" people gather :D I'm sure programmers know how to tweak their environment.

That is what you think ;)

Only 5 minutes ago i had a college where the DVI cable was changed and he was struggling to change the primary monitor from the first to the second screen. And some other "simple" issues.

Your falling for the myth that if a person is IT, he must know everything IT related. Like the 1000 of people asking me about Outlook, Access etc when i do not work with them, so how am i supposed to know where x is or how to solve y.

The problem is with D and any "product", the more steps it needs from the end user, the more troublesome it is and the less people are interested into it. Having people set the path, without it even being mention in the readme, is definitely not consumer friendly.

**Comment by vladimmi** [comment]
That's a bit off-topic, but "IT" and "programmer" is kinda different things... I mean, D is not a product to "install and use", you should have some good skills because you will develop software. Also knowing Outlook doesnt relate to your job as programmer, but knowing basic OS things (like environment variables, console usage, shell scripts) is required. But yes, sure, it should be noted somewhere in readme that you need to do that to make things actually work.

Also talking about serve-d and vscode, you can avoid using PATH and just set path to serve-d or ldc or anything else at vscode's user or workspace settings (File - Settings - D options subtree).

**Comment by Wulfklaue** [comment]
Define programmer :)  System programmer, web programmer are all programmers and yet, there can be a huge gap in skills. Let alone between a junior and senior programmer. ;)

> Also talking about serve-d and vscode, you can avoid using PATH 
You just proved my point. I did not know it was possible to do that. So my 20+ years of professional experience was useless and failed me. :)

But again, consumer friendly it is not... Its a issue i have run into especially with D, where too many things are based upon "assumed" knowledge of the matter. Things that just work in other language because of installers or better documentation.

Yesterday i posted the simple command lines to install LDC onto a ARM device on the forum. Because again, LDC download is available but it does not show people how to install it properly, making them hunt for it.

D as a language can be used by less skilled programmers or even new people but the constant issues like this make it harder for people to get there hand wet. That makes people give up early and affects the growth of the language. 

Major off-topic. Its the same with the constant issue with Code-D and Serve-D. I can go back almost a year of non-stop running into issues with Code-D ( and now also Serve-D), that makes me regret the language. I love the language but boy, does everything beside the language make you suffer too much.

I end up going to other languages to get my mini-projects done, simply because its a hassle with D all the time, where as Go or C# just work. I understand its a volunteer project but i stated many times before that D NEEDS to have people who are paid and work on the eco-system of the language and not just pure on the language. I have no problem donating, did the same with Nim but i do not want my money to go to more language improvement when there is a clear focus needs to be the whole eco-system first. User friendly, better IDE support, ... It can not be that a handful of none paid people need to keep things going. It does not work like that. 

/Rant 👍

**Comment by WebFreak001** [comment]
it's still not installable with dmd, don't close this

**Comment by WebFreak001** [comment]
fixed in https://github.com/Pure-D/workspace-d/commit/0e9b4b501dfd223a4210bb333d803711977adffb
