### ISSUE TITLE
serve-d complains when on assignment in conditional expression

### ISSUE THREAD

**Issue by vabenil** [Pure-D/serve-d#228]
### Description
Serve-d tells me that the code below should result in an Error despite it compiling fine.
![2022-06-03_10:55:50](https://user-images.githubusercontent.com/100315855/171813379-8ebe996b-3c52-461c-b243-9c14df3c4e0d.png)

### Setup
- Arch Linux
- neovim 0.7.0
- nvim-lspconfig
- serve-d - latest version as of June 03 2022 (Also tested with stable 7.4v release)

### Steps to reproduce
1. Create a sample project with dub
2. insert this code in source/app.d
```d
import std : writeln, format;

void main()
{
    int i = 10;
    // Silly example I know
    while (int not_four = (i != 4)) {
        writeln(format("%d is not 4!", i));
        i--;
    }
}
```

**Comment by WebFreak001** [comment]
this actually seems to be new syntax since 2.097.2 that you are allowed to use variable declarations as conditions inside while loops that's not yet supported in libdparse: https://dlang.org/changelog/2.097.0.html#while-condition-assignment

**Comment by vabenil** [comment]
Should I open an issue in libdparse then?

**Comment by WebFreak001** [comment]
yes, should be fixed soon too

**Comment by WebFreak001** [comment]
(still needs libdparse update here)

**Comment by vabenil** [comment]
`libdparse` has already updated here. The only thing we are missing is a release. We can close this already, no?

**Comment by WebFreak001** [comment]
yep, stable release is in preparation and dependencies are updated as well
