### ISSUE TITLE
dub build fails on freebsd (but can be fixed)

### ISSUE THREAD

**Issue by devosalain** [Pure-D/serve-d#251]
1. using gcc as compiler, i.e.  
```
export CC=/usr/local/bin/gcc
```

2.modifying ./serverbase/dub.sdl
```
dependency "serve-d:lsp" path="../lsp"
```

3.modifying ./workspace-d/dub.sdl
```
dependency "serve-d:dcd" path="../dcd"
```

After this "dub build" builds just fine.

**Comment by WebFreak001** [comment]
which dub version are you using? this shouldn't be happening on recent dub versions

**Comment by devosalain** [comment]
dub --version
DUB version 1.14.0, built on Jul  3 2022

**Comment by WebFreak001** [comment]
1.14 is very old and is probably too outdated at this point. The current version is 1.29, does your distro distribute a newer version like that? It might be worth fixing the distro's version instead, as dub changed the recommended way how to refer to submodules, which is being used right now, but not compatible with old dub versions.

**Comment by devosalain** [comment]
Thanks , i entered a PR for my distro,
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265606

**Comment by WebFreak001** [comment]
fixed upstream
