### ISSUE TITLE
want textDocument/references....

### ISSUE THREAD

**Issue by gdamore** [Pure-D/serve-d#261]
While trying to this with Helix editor, I find that while I can often navigate from a call site to a definition, I cannot go from a definition to references -- this is a super useful capability that I've used in numerous different editors in the past (e.g. IntelliJ, even VSC) -- the ability to find call sites for a function or symbol references. 

I realize with D the problem is "hard" (because mixins, traits, and templates -- although templates are probably easier than the other two to deal with), but at least we could try to resolve for the easier cases.

The error that the editor shows is "Async job failed: protocol error: MethodNotFound: Request method textDocument/references not found".

I guess this is part of the LSP spec that is missing.

**Comment by WebFreak001** [comment]
fixed in master, improvements will come in the future
