### ISSUE TITLE
Incorrect folding region

### ISSUE THREAD

**Issue by ryuukk** [Pure-D/serve-d#264]
VScode released a new feature: sticky scroll, it allows header of folding regions to stick when you scroll

Setting: ``"editor.stickyScroll.enabled": true,``

How it should look:

![image](https://user-images.githubusercontent.com/44361234/198858793-ca3aead9-5e60-4fe6-a956-84ba17823c56.png)

How it looks on D code:

![image](https://user-images.githubusercontent.com/44361234/198858697-a667014e-b248-437c-a04b-57743ff11d8b.png)

**EDIT:**

It only works when the brackets start on the same line at the folding header

![image](https://user-images.githubusercontent.com/44361234/198858822-5766d1db-54de-4ab4-86c7-878c3ebc4e11.png)

When it's on a new line it doesn't, so the range should account for that in serve-d

**Comment by WebFreak001** [comment]
sticky scroll doesn't use the folding regions, you need to open or vote on an issue there if you want that. Folding regions can definitely be improved though.
