### ISSUE TITLE
OpenSSL error when launching LSP from neovim

### ISSUE THREAD

**Issue by cheeze2000** [Pure-D/serve-d#269]
```
"object.Exception@../../../.dub/packages/requests-1.1.7/requests/source/requests/ssl_adapter.d(193): loading openssl: unknown version for init\n"
```
![image](https://user-images.githubusercontent.com/26966445/200171550-c4c5d692-f4fc-4d1a-8b34-d7a81a948431.png)

<https://github.com/Pure-D/serve-d/pull/227> Perhaps ~~the library needs to be bumped again?~~ a new release?

**Comment by cheeze2000** [comment]
I should have tried the nightly version, I don't know why it took me so long to realise that.

**Comment by WebFreak001** [comment]
you need to either build from source or download a precompiled beta (pre-release) or from the [nightly tag](https://github.com/Pure-D/serve-d/releases/nightly)
