### ISSUE TITLE
Error on shutdown

### ISSUE THREAD

**Issue by LaurentTreguier** [Pure-D/serve-d#32]
I'm testing Serve-D in Atom, and on exit Atom complains:
![image](https://user-images.githubusercontent.com/7602755/38828604-dfecf682-41b6-11e8-9b12-548c67fdbd44.png)
Apparently Serve-D sends a response without any `result or `error` property. Given that it happens on shutdown, I thought it was the `shutdown` response that was responsible, but it looks like [it does send a null response](https://github.com/Pure-D/serve-d/blob/master/source/served/extension.d#L404). Could Serve-D actually not be taking the result property into account because it's null ? (I encountered this problem with my language server; VSCode didn't seem to mind it but Atom did)

Apart from this issue, things seem to work smoothly in Atom 👍

**Comment by WebFreak001** [comment]
https://microsoft.github.io/language-server-protocol/specification#shutdown

the server is supposed to return null, the return value there is used in the response: https://github.com/Pure-D/serve-d/blob/master/source/app.d#L79

everything is according to the specs on serve-d side

**Comment by LaurentTreguier** [comment]
Looking at Serve-D's logs, it does send a response without any result or error:
![image](https://user-images.githubusercontent.com/7602755/38832161-00a676b8-41c2-11e8-80e4-f001e7a6f77f.png)

**Comment by WebFreak001** [comment]
oh right sending null for result is omitting it in the field because it needs to have support to only send an error instead of both: https://github.com/Pure-D/serve-d/blob/master/source/served/jsonrpc.d#L43

hm not sure how to properly change that though

**Comment by LaurentTreguier** [comment]
How about making `result` in `ResponseMessage` an `Optional!JSONValue` ? This would differentiate having no value and having a `null` value
