### ISSUE TITLE
Error compiling 'requests' 1.1.7, what version should I use?

### ISSUE THREAD

**Issue by pinver** [Pure-D/serve-d#339]
I've seen that in #308 the suggestion is to use the pre-release or master branch, but the release after 1.1.7 is 2.x.x.

Any suggestion on a tested working release?

**Comment by WebFreak001** [comment]
you need to use the beta or nightly serve-d versions. In vscode to automatically get them you change the setting s.servedReleaseChannel and reload the window

**Comment by redthing1** [comment]
Just go the directory it tries to compile served, checkout master, build, then set the path in settings
