### ISSUE TITLE
serve-d doesn't work anymore (openssl) problem

### ISSUE THREAD

**Issue by MonoMaxMW** [Pure-D/serve-d#352]
Hello serve-d stopped working.
I'm using the "nightly" edition

Archlinux x64

Below the log:

object.Exception@../../../.dub/packages/requests/2.1.1/requests/source/requests/ssl_adapter.d(204): loading openssl: unknown version Tuple!(int, "major", int, "minor")(3, 2) for init
[Info  - 9:47:26 AM] Connection to server got closed. Server will restart.
object.Exception@../../../.dub/packages/requests/2.1.1/requests/source/requests/ssl_adapter.d(204): loading openssl: unknown version Tuple!(int, "major", int, "minor")(3, 2) for init
[Info  - 9:47:26 AM] Connection to server got closed. Server will restart.
object.Exception@../../../.dub/packages/requests/2.1.1/requests/source/requests/ssl_adapter.d(204): loading openssl: unknown version Tuple!(int, "major", int, "minor")(3, 2) for init
[Info  - 9:47:26 AM] Connection to server got closed. Server will restart.
object.Exception@../../../.dub/packages/requests/2.1.1/requests/source/requests/ssl_adapter.d(204): loading openssl: unknown version Tuple!(int, "major", int, "minor")(3, 2) for init
[Info  - 9:47:26 AM] Connection to server got closed. Server will restart.
object.Exception@../../../.dub/packages/requests/2.1.1/requests/source/requests/ssl_adapter.d(204): loading openssl: unknown version Tuple!(int, "major", int, "minor")(3, 2) for init
[Info  - 9:47:26 AM] Connection to server got closed. Server will restart.
object.Exception@../../../.dub/packages/requests/2.1.1/requests/source/requests/ssl_adapter.d(204): loading openssl: unknown version Tuple!(int, "major", int, "minor")(3, 2) for init
[Info  - 9:47:26 AM] Connection to server got closed. Server will restart.
object.Exception@../../../.dub/packages/requests/2.1.1/requests/source/requests/ssl_adapter.d(204): loading openssl: unknown version Tuple!(int, "major", int, "minor")(3, 2) for init
[Info  - 9:47:26 AM] Connection to server got closed. Server will restart.
object.Exception@../../../.dub/packages/requests/2.1.1/requests/source/requests/ssl_adapter.d(204): loading openssl: unknown version Tuple!(int, "major", int, "minor")(3, 2) for init
[Info  - 9:47:26 AM] Connection to server got closed. Server will restart.
object.Exception@../../../.dub/packages/requests/2.1.1/requests/source/requests/ssl_adapter.d(204): loading openssl: unknown version Tuple!(int, "major", int, "minor")(3, 2) for init
[Info  - 9:47:26 AM] Connection to server got closed. Server will restart.
object.Exception@../../../.dub/packages/requests/2.1.1/requests/source/requests/ssl_adapter.d(204): loading openssl: unknown version Tuple!(int, "major", int, "minor")(3, 2) for init
Server crashed 10 times in the last minute. The server will not be restarted.
[Error - 9:47:27 AM] Connection to server got closed. Server will not be restarted.

**Comment by vabenil** [comment]
I have exactly the same issue. This started happening when I upgraded Arch Linux ~3 days ago.

**Comment by WebFreak001** [comment]
upstream issue: https://github.com/ikod/dlang-requests/issues/161

**Comment by snprajwal** [comment]
When will this be released? Or is there a workaround to make serve-d work until the next release is cut?

**Comment by snprajwal** [comment]
Just saw that the last pre-release was published in Sep 2023, could we please cherry-pick this commit (if we don't want any of the others), and cut a hotfix release or something? I wouldn't want my LSP to depend on a local build unless I'm making changes to serve-d myself.

**Comment by WebFreak001** [comment]
you can set the `d.servedReleaseChannel` setting to nightly to get the latest master build, but yeah cherry picking this is a good idea

**Comment by snprajwal** [comment]
> you can set the `d.servedReleaseChannel` setting to nightly to get the latest master build, but yeah cherry picking this is a good idea

It looks like coc-dlang does not have this configuration option (I'm not using code-d). Thanks for the release, it fixed it for me!
