### ISSUE TITLE
OOM crash on std.internal.unicode_tables.d

### ISSUE THREAD

**Issue by dkorpel** [Pure-D/serve-d#353]
When opening https://github.com/dlang/phobos/blob/7b94cd0e77e6b709e40e8517feca3423daa0d204/std/internal/unicode_tables.d and serve-d requests information (e.g. go to symbol, hover tool tips), it starts allocating memory until it fills all of my 32 GB and then my desktop crashes.

It's a challenging file with very large array literals (which I recall libdparse being bad at), but at least I'd like an option to disable serve-d on certain files I specify, or cap the memory allocations to something lower than my system's maximum so it doesn't crash the desktop.

**Comment by WebFreak001** [comment]
fixed with https://github.com/dlang-community/DCD/pull/768 already
