### ISSUE TITLE
DCD is not downloaded

### ISSUE THREAD

**Issue by philippludwig** [Pure-D/serve-d#375]
I am trying to use serve-d with Emacs and eglot. When I run eglot from Emacs, I get:

```
[eglot] Server reports (type=1):  DCD is outdated. (target=0.13.6, installed=none)
Choose an option:  Download DCD
```

I press Return, then nothing happens.

So how do I download DCD? I could not find anything in the Troubleshooting guide, except that it is supposed to happen automatically.

**Comment by WebFreak001** [comment]
you can install DCD system wide from https://github.com/dlang-community/DCD, then serve-d should use that

You might need to enter "Download DCD" for it to trigger that action, I don't actually know how eglot handles notifications with buttons (which is what this message is)

**Comment by philippludwig** [comment]
Works perfectly. I just downloaded the binaries and put it next to the serve-d binary. The message for Downloading DCD does not appear anymore.
