### ISSUE TITLE
Consistent crashes and instability when waking laptop from sleep state

### ISSUE THREAD

**Issue by spikespaz** [Pure-D/serve-d#43]
After much frustration and the constant "serve-d has crashed 5 times in the last 3(?) minutes" from VS Code `code-d` extension, I've finally realized that it happens most often after opening my laptop lid and waking from sleep. Serve-D server works fine until my laptop goes to sleep.

Relevant information:
OS Build: `177713`, Windows 10 Home Insider Preview
Laptop: Dell Inspiron 7559 (Upgraded significantly)

Serve-D version output:
```
serve-d v0.1.3 with workspace-d v2.12.0
Included features: "d"
Built: Sun Jul  1 22:18:22 2018
```
(Built by me on LLVM/LDC2)

I would really really love to see this issue fixed as it is quite infuriating. I have no proof that the sleep issue is the actual cause of the crashing and instability, but it is the only consistent thing that I can see. If any more information is needed I would be more than happy to help.

**Comment by WebFreak001** [comment]
can you check what the output log says when it does crash? It could not be related with sleeping but instead for example with dparse crashing on incomplete code, which I have noticed recently

**Comment by spikespaz** [comment]
@WebFreak001 I'm not sure, but I think this is what you're looking for. If this is wrong let me know.
https://pastebin.com/raw/RtwUczqZ

**Comment by WebFreak001** [comment]
retry in code-d 0.21.0 with serve-d 0.5.1 again and reopen if it still happens
