### ISSUE TITLE
Windows Defender deleting serve-d executable because it contains a Fuery.B!cl Trojan

### ISSUE THREAD

**Issue by Cody-Duncan** [Pure-D/serve-d#48]
Windows Defender is reporting that the serve-d.exe contains a Fuery.B!cl trojan.

**serve-d executable downloaded manually from:** 
https://github.com/Pure-D/serve-d/releases/download/v0.3.0/serve-d_0.3.0-windows.zip

**Results:**
When visual studio code tries to install and spin up serve-d.exe, it fails with error message:
```
[Error - 11:47:08 PM] Starting client failed
Error: spawn UNKNOWN
	at _errnoException (util.js:1024:11)
	at ChildProcess.spawn (internal/child_process.js:323:11)
	at Object.exports.spawn (child_process.js:514:9)
	at _getServerWorkingDir.then.serverWorkingDir (C:\Users\Dragon\.vscode\extensions\webfreak.code-d-0.19.0\node_modules\vscode-languageclient\lib\main.js:346:40)
	at <anonymous>
```

**Report from Windows Defender:**
```
Trojan:Win32/Fuery.B!cl

Alert level: Severe
Status: Quarantined
Date: 10/4/2018

Recommended action: Remove thread now.

Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

Affected items:
C:\Utils\Dlang\serve-d_0.3.0-windows\serve-d.exe
```

**Comment by WebFreak001** [comment]
compile it yourself or tell windows defender it's a false positive

**Comment by Cody-Duncan** [comment]
Instructions for adding exception:
https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-security
