### ISSUE TITLE
Color syntax issue

### ISSUE THREAD

**Issue by Wulfklaue** [Pure-D/serve-d#5]
Not sure if this is part of Serve-d or not.

public void decrypt(string keyring, string passphrase, string decrypte_filename, string **out**put_filename)

output_filename will have the "out" part showing in purple color, while the rest is light blue. It looks like the "out" keyword check is not checking if there is text behind it = variable.

**Comment by WebFreak001** [comment]
part of code-d

**Comment by WebFreak001** [comment]
Just published the release fixing this
