### ISSUE TITLE
Multiple DCD instances running

### ISSUE THREAD

**Issue by Pulgovisk** [Pure-D/serve-d#53]
After 30mins of code editor, i have  4 dcd-servers launched
![print](https://user-images.githubusercontent.com/15163685/51134416-a6eac500-181e-11e9-8e03-c7acb0791503.png)

**Comment by WebFreak001** [comment]
hi, do you have multiple dub.json/dub.sdl files or multiple workspaces? For every workspace there is one dcd-server instance. There should just be one serve-d instance and when you close vscode all dcd-servers will close, which indicates that everything works properly then

**Comment by Pulgovisk** [comment]
No, i only have one workspace open with one dub.json file in there.
The projects is [xdg-d-generator](https://github.com/Pulgovisk/xcb-d-generator)

**Comment by WebFreak001** [comment]
can you send code-d logs?

**Comment by Pulgovisk** [comment]
Off curse, [code-d.log](https://github.com/Pure-D/serve-d/files/2756728/code-d.log)

**Comment by Pulgovisk** [comment]
Now i have 6 dcd-server running
![image](https://user-images.githubusercontent.com/15163685/51135377-021db700-1821-11e9-98a0-0b0c749583c2.png)

**Comment by Pulgovisk** [comment]
This not fix the build issue
````
C:\Temp\serve-d>dub build --arch=x86_mscoff --cache=local
Invalid source/import path: C:\Users\Jo├úo Paulo\AppData\Local\dub\packages\dfmt-0.9.0\dfmt\bin
Running pre-generate commands for dfmt...
Error: module `JoÒo` is in file 'C:\Users\JoÒo.d' which cannot be read
import path[0] = C:\Users
import path[1] = C:\D\dmd2\windows\bin\..\..\src\phobos
import path[2] = C:\D\dmd2\windows\bin\..\..\src\druntime\import
Failed: ["C:\\D\\dmd2\\windows\\bin\\dmd.exe", "-v", "-o-", "C:\\Users\\Jo├úo.d", "-IC:\\Users"]
Command failed with exit code 1: rdmd C:\Users\Jo├úo Paulo\AppData\Local\dub\packages\dfmt-0.9.0\dfmt/dubhash.d
````

**Comment by WebFreak001** [comment]
hm seems like the cache argument didn't work, it should put dependencies inside your local folder. As a hack you can workaround this by changing `C:\Users\Jo├úo Paulo\AppData\Local\dub\packages\dfmt-0.9.0\dub.json` and where it says `"rdmd $PACKAGE_DIR/dubhash.d"` near the end you replace it with `"rdmd \"$PACKAGE_DIR/dubhash.d\""`

You also need to do that with the latest dscanner package you have in your dub packages folder

**Comment by Pulgovisk** [comment]
I will try to delete the %LOCALAPPDATA%/dub/packages and run the dub with --cache=system, for cache in `C:\ProgramData\dub`

**Comment by Pulgovisk** [comment]
> I will try to delete the %LOCALAPPDATA%/dub/packages and run the dub with --cache=system, for cache in `C:\ProgramData\dub`

This work. After the build succeed, what i do?

**Comment by WebFreak001** [comment]
now just set `"d.servedPath"` in your user settings to the new serve-d.exe

**Comment by Pulgovisk** [comment]
After this setting, code-d fails to install DCD
```
Installing DCD
Downloading from https://github.com/dlang-community/DCD/releases/download/v0.10.2/dcd-v0.10.2-windows-x86.zip to C:\Users\João Paulo\AppData\Roaming\code-d\bin
Failed installing: std.net.curl.CurlException@std\net\curl.d(4365): Peer certificate cannot be authenticated with given CA certificates on handle 1A72960
----------------
0x00D6DB87 in std.exception.bailOut!(std.net.curl.CurlException).bailOut at C:\D\dmd2\windows\bin\..\..\src\phobos\std\exception.d(515)
0x00D66C9A in std.exception.enforce!(std.net.curl.CurlException).enforce!bool.enforce at C:\D\dmd2\windows\bin\..\..\src\phobos\std\exception.d(437)
0x00DB07B6 in void std.net.curl.Curl._check(int)
0x0096143F in std.net.curl.download!(std.net.curl.HTTP).download at C:\D\dmd2\windows\bin\..\..\src\phobos\std\net\curl.d(431)
0x009611EC in std.net.curl.download!(std.net.curl.AutoProtocol).download at C:\D\dmd2\windows\bin\..\..\src\phobos\std\net\curl.d(440)
0x0094F3D7 in served.commands.dcd_update.updateDCD at C:\Temp\serve-d\source\served\commands\dcd_update.d(113)
0x0091C848 in std.functional.DelegateFaker!(void function()).DelegateFaker.doIt at C:\D\dmd2\windows\bin\..\..\src\phobos\std\functional.d-mixin-1430(1442)
0x00D8465D in void core.thread.Fiber.run()
```

**Comment by Pulgovisk** [comment]
After the update the problem is fixed.
But the dowload error is not fixed.
