### ISSUE TITLE
Possible memory leak on Windows?

### ISSUE THREAD

**Issue by tekord** [Pure-D/serve-d#58]
Hi! Thanks for this tool. I trying to use it with VS Code, installed this extension https://marketplace.visualstudio.com/items?itemName=webfreak.code-d. It uses serve-d. It works, but after some time serve-d process takes more and more memory and never frees it. Started from ~9.3 Mb, raised to 300 after coding of 2 functions in my module with using autocomplete.

I noticed that each autocomplete request cause growing of memory usage by ~1Mb. Sometimes by 4-5Mb.

**Comment by WebFreak001** [comment]
Can you try again with serve-d 0.5.1?

**Comment by WebFreak001** [comment]
closing until reconfirmed
