### ISSUE TITLE
What unit does serve-d use in lsp ranges?

### ISSUE THREAD

**Issue by Avi-D-coder** [Pure-D/serve-d#59]
Does this project use UTF-8, UTF-16, codepoint, or grapheme cluster indexes for lsp ranges?

I am conducting a [survey](https://github.com/Avi-D-coder/lsp-range-unit-survey) to inform the debate over what unit ranges should use in the [Language Server Protocol](https://github.com/Microsoft/language-server-protocol).
The debate is occuring in [issue #376](https://github.com/Microsoft/language-server-protocol/issues/376).

**Comment by WebFreak001** [comment]
we work with UTF-8 code units internally (regular D encoding) and encode/decode UTF-16 code units for any protocol related stuff

See https://github.com/Pure-D/serve-d/blob/master/source/served/textdocumentmanager.d#L35-L141 for implementation
