### ISSUE TITLE
CPU 100% on macOS

### ISSUE THREAD

**Issue by zoujiaqing** [Pure-D/serve-d#60]
for macOS version:
```bash
osx:projects zoujiaqing$ uname -a
Darwin osx 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

for dmd & dub:
```bash
osx:projects zoujiaqing$ dub --version
DUB version 1.13.0, built on Jan  1 2019
osx:projects zoujiaqing$ dmd --version
DMD64 D Compiler v2.084.0
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright
```

VSCode version:
```txt
1.32.3
```

code-d version:
```txt
0.20.2
```
<img width="800" alt="serve-d" src="https://user-images.githubusercontent.com/444820/55153964-b6777a00-518e-11e9-94bf-46c1b1dd95c6.png">

**Comment by WebFreak001** [comment]
Are you saving often? Can you try setting `"d.enableDubLinting": false` in your user settings and see if it still happens? It could be because for every save it will start a dub build to lint the project

**Comment by zoujiaqing** [comment]
Thanks, I try : )

**Comment by WebFreak001** [comment]
anything new?

**Comment by zoujiaqing** [comment]
Still unresolved ..

**Comment by torarvid** [comment]
I just noticed this on my macOS as well. It stayed at 100% after I closed all VS Code windows, and even after I quit the VS Code app altogether. (So at least to me it sounds like it's not doing any "saving of files" at this point... 🤷🏼‍♂️)

**Comment by WebFreak001** [comment]
does it spam `PosixStdinReader error in select()` or `PosixStdinReader error in read()` in the code-d output tab?

**Comment by zoujiaqing** [comment]
100% on Debian GNU/Linux ..
![WechatIMG4](https://user-images.githubusercontent.com/444820/59184421-ae7d8280-8ba0-11e9-92ab-4c1dcfbe3c72.png)

**Comment by WebFreak001** [comment]
can you send the log in the code-d & serve-d output panel?

**Comment by WebFreak001** [comment]
try again with serve-d 0.5.1
