### ISSUE TITLE
"stdlibPath"="auto" should auto detect path from dmd path

### ISSUE THREAD

**Issue by finalpatch** [Pure-D/serve-d#61]
Right now it uses hard coded paths. If the user installs dmd to a different location than serve-d will fail to locate library files.  I think it's better to derive the default lib paths from dmd executable path.

**Comment by WebFreak001** [comment]
For windows it seems to be in `../../src/` relative to the dmd.exe, on linux I could probably read /etc/dmd.conf (becuase relative paths are different), on OSX I don't think there is any need for this (also can't test)

Is that what you had in mind?

**Comment by finalpatch** [comment]
@WebFreak001 I just realise that dmd actually prints out its config file when invoked with no arguments.
Wouldn't this be a much more reliable way to detect standard lib paths?

**Comment by WebFreak001** [comment]
you're right that would work a lot better and would prevent a lot of headaches. I will add that to Pure-D/code-d#255

**Comment by finalpatch** [comment]
This will work for the case of people calling dmd through a shim executable.
