### ISSUE TITLE
Use DCD as library 

### ISSUE THREAD

**Issue by andre2007** [Pure-D/serve-d#63]
Could you consider using DCD, as library instead of calling the executables?

This is the way how DLS is working and the speed and stability of code completion is overwhelming in contrast of calling DCD client executable for every request (how Intellij D plugin is currently implemented).

**Comment by WebFreak001** [comment]
already doing this

**Comment by WebFreak001** [comment]
well to extend on this: I kept DCD separate because of many memory issues and segfaults, which have improved but for now I will keep it separate, but if you want that to be included too you can rename and reopen the issue

**Comment by andre2007** [comment]
Yes, I was confused because there was the download of DCD executable and file handling here: https://github.com/Pure-D/serve-d/blob/master/source/served/commands/dcd_update.d#L3
Therefore I thought it isn't implemented yet.

Calling on each code completion request an executable which calls via tcp to a server is almost unusable slow and error prone. I think I measured in the past 1000 requests. The difference was 20 minutes vs 40 seconds.

I rename the issue as proposed.

**Comment by andre2007** [comment]
I am not allowed to reopen it.

**Comment by WebFreak001** [comment]
using dcd-client as a library would probably make sense but I would still keep dcd-server separate to avoid issues there for now. I don't know if it's really a good idea integrating dcd-server right now because it will make serve-d even bigger than it currently is (about 80 MB)

**Comment by andre2007** [comment]
I do not know the details here, I just wonder because DLS has a size of < 2 MB. 
(Maybe as info for you, the author of DLS said he would still fix errors but do not plan to add new features).

**Comment by WebFreak001** [comment]
ah guess it's not that bad actually, with dmd debug + strip it's 28 MB, with ldc release it's 11 MB and with ldc release + strip it's 7.5 MB

**Comment by 0xEAB** [comment]
I'd not use DCD as a library. Would make `serve-d` unstable. Don't believe me? Have a look at DLS.

**Comment by andre2007** [comment]
I do not want to make serve-d unstable. But why do you think, would removing the unstable exe+TCP layer impact the stability of serve-d? At the moment I only can think of reasons why the stability would increase.

**Comment by LaurentTreguier** [comment]
DLS isn't 2 MB in size. The zip archive I redistribute is small, but the unzipped executable is 7 MB on Linux, 5 on Windows and something else on macOS.
It would make serve-d more unstable because any crash from DCD would crash serve-d itself. Right now serve-d can just respawn dcd-server as needed.

**Comment by andre2007** [comment]
My experience with the communication channel (IDE is calling DCD client executable which calls DCD server via TCP) was frustrating. While working on a high end computer the performance was not acceptable. A lot of other developers even do not get it working at all.

By switching to DLS immediately the code completion performance was on pair with commercial solutions. DCD is fast, the communication channel is the issue. Even the stability increased. 

An idea in the past was to add a STDIO channel in addition to TCPIP to DCD server. But it was not done because here we would rebuild LSP.

I close this issue due to the concerns.

**Comment by WebFreak001** [comment]
I still plan on adding dcd-client as a library with this

**Comment by WebFreak001** [comment]
dcd-client is used as a library now
