### ISSUE TITLE
Crashing on Windows

### ISSUE THREAD

**Issue by SrMordred** [Pure-D/serve-d#64]
v0.4.1 binary crashes with 0cx00007b error.
v0.4.0 works fine.

Win 10 x64.

**Comment by WebFreak001** [comment]
can you try updating DCD? Nothing has changed between the releases except the bundled DCD version and a small fix in the DCD installer

**Comment by SrMordred** [comment]
I got here because of VSCode code-d plugin. (giving me "Connection to server got closed" 20 times)
Since it download dcd-server and client + serve-d i believe that it all must be on the right versions.
So i tried to execute by hand the binary and then found the crash on serve-d.

**Comment by WebFreak001** [comment]
try `"d.betaStream": true` in your user settings to make it compile the latest commit to see if that fixes the issue

**Comment by SrMordred** [comment]
dub build --arch=x86_mscoff
Unsupported architecture: x86_mscoff
Failed to install serve-d (Error code 2)

**Comment by WebFreak001** [comment]
do you have the latest code-d version? that should be fixed already but I'm not sure if it's released yet

**Comment by SrMordred** [comment]
Version: 0.20.2

**Comment by WebFreak001** [comment]
try again with serve-d 0.5.1 (code-d side will be fixed with next release)
