### ISSUE TITLE
Current version is unusable with Neovim

### ISSUE THREAD

**Issue by whitebyte** [Pure-D/serve-d#69]
Hi, I'm not using workspace-d directly but as a part of serve.d. After the last update virtually every LSP function in Neovim stopped working. Below is an excerpt from the LSP client log:

` Message: {"error":{"code":-32603,"data":"object.Exception@/home/eyes/.dub/packages/workspace-d-3.2.0/workspace-d/source/workspaced/api.d(527): cwd '/home/eyes/misk/d/dgame' not found\n----------------\n??:? workspaced.com.dscanner.DscannerComponent workspaced.api.WorkspaceD.get!(workspaced.com.dscanner.DscannerComponent).get(immutable(char)[]) [0xff4834dc]\n??:? served.protocol.SymbolInformation[] served.extension.provideDocumentSymbols(served.protocol.DocumentSymbolParams) [0xff418c5e]\n??:? served.protocol.ResponseMessage app.processRequest(served.protocol.RequestMessage) [0xff37de39]\n??:? void app.main(immutable(char)[][]).__lambda7() [0xff38132f]\n??:? void core.thread.Fiber.run() [0x57647f97]\n??:? fiber_entryPoint [0x57647362]\n??:? [0xffffffff]","message":"cwd '/home/eyes/misk/d/dgame' not found"},"jsonrpc":"2.0"}
`

Most of the error messages from other methods (goto definition, show project symbols, request completion etc) blame `workspace-d-3.2.0/workspace-d/source/workspaced/api.d(527)`
 as well, since this bugreport is here and not in the serve-d repo.

serve-d, workspace-d, DCD, Dscanner are all fresh from Github.

**Comment by WebFreak001** [comment]
can you try again now? Now startup should work properly and thus also fixing the broken features
