### ISSUE TITLE
Support UTF-8 for the LSP protocol

### ISSUE THREAD

**Issue by XVilka** [Pure-D/serve-d#70]
See the lengthy discussion here: https://github.com/microsoft/language-server-protocol/issues/376

It seems that serve-d is one of a few that uses UTF-16 https://github.com/Avi-D-coder/lsp-range-unit-survey

Would be nice if it will have UTF-8 support as well, at least optionally.

**Comment by WebFreak001** [comment]
serve-d it's using UTF-16 only for compatibility with the spec/vscode. Internally it works with UTF-8 and using UTF-8 would be a little bit faster too.

Simply changing all the `wchar` in [this file](https://github.com/Pure-D/serve-d/blob/master/source/served/textdocumentmanager.d#L108) to `char` would change support to UTF-8 and changing them to `dchar` would change support to UTF-32

When there is some mechanism to support exchanging the charset to use, this is a trivial thing to change

**Comment by WebFreak001** [comment]
not gonna change unless spec requires it
