### ISSUE TITLE
Use default dfmt configuration that supports .editorconfig

### ISSUE THREAD

**Issue by carun** [Pure-D/serve-d#96]
[dfmt](https://github.com/dlang-community/dfmt) uses `.editorconfig` by default. But serve-d/code-d doesn't invoke dfmt to use .editorconfig, but passes settings from user settings JSON.

Think of this use case where we need to work on different projects and each have different formatting styles, captured in their own `.editorconfig`. It would be good if serve-d/code-d can respect that by invoking dfmt with the project specific `.editorconfig`, there by we don't have to fix our user settings JSON every time we have to work on a different project.

One of the approaches would be to create `.editorconfig` if the file doesn't exist. Over the time this could become a standard practice as well.

**Comment by WebFreak001** [comment]
merging into #213
